// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/repositories/world (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go -package=worldmock github.com/KirkDiggler/rpg-api/internal/repositories/world Repository
//

// Package worldmock is a generated GoMock package.
package worldmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	world "github.com/KirkDiggler/rpg-api/internal/repositories/world"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(arg0 context.Context, arg1 *world.GetInput) (*world.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*world.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), arg0, arg1)
}

// SetMemberRoles mocks base method.
func (m *MockRepository) SetMemberRoles(arg0 context.Context, arg1 *world.SetMemberRolesInput) (*world.SetMemberRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemberRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetMemberRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMemberRoles indicates an expected call of SetMemberRoles.
func (mr *MockRepositoryMockRecorder) SetMemberRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemberRoles", reflect.TypeOf((*MockRepository)(nil).SetMemberRoles), arg0, arg1)
}

// SetRoles mocks base method.
func (m *MockRepository) SetRoles(arg0 context.Context, arg1 *world.SetRolesInput) (*world.SetRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockRepositoryMockRecorder) SetRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockRepository)(nil).SetRoles), arg0, arg1)
}
