// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/auth (interfaces: TokenValidator,MembershipVerifier)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_discord.go -package=authmock github.com/KirkDiggler/rpg-api/internal/auth TokenValidator,MembershipVerifier
//

// Package authmock is a generated GoMock package.
package authmock

import (
	context "context"
	reflect "reflect"

	auth "github.com/KirkDiggler/rpg-api/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenValidator is a mock of TokenValidator interface.
type MockTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenValidatorMockRecorder
	isgomock struct{}
}

// MockTokenValidatorMockRecorder is the mock recorder for MockTokenValidator.
type MockTokenValidatorMockRecorder struct {
	mock *MockTokenValidator
}

// NewMockTokenValidator creates a new mock instance.
func NewMockTokenValidator(ctrl *gomock.Controller) *MockTokenValidator {
	mock := &MockTokenValidator{ctrl: ctrl}
	mock.recorder = &MockTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenValidator) EXPECT() *MockTokenValidatorMockRecorder {
	return m.recorder
}

// GetCurrentUser mocks base method.
func (m *MockTokenValidator) GetCurrentUser(ctx context.Context, token string) (*auth.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx, token)
	ret0, _ := ret[0].(*auth.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockTokenValidatorMockRecorder) GetCurrentUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockTokenValidator)(nil).GetCurrentUser), ctx, token)
}

// MockMembershipVerifier is a mock of MembershipVerifier interface.
type MockMembershipVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipVerifierMockRecorder
	isgomock struct{}
}

// MockMembershipVerifierMockRecorder is the mock recorder for MockMembershipVerifier.
type MockMembershipVerifierMockRecorder struct {
	mock *MockMembershipVerifier
}

// NewMockMembershipVerifier creates a new mock instance.
func NewMockMembershipVerifier(ctrl *gomock.Controller) *MockMembershipVerifier {
	mock := &MockMembershipVerifier{ctrl: ctrl}
	mock.recorder = &MockMembershipVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipVerifier) EXPECT() *MockMembershipVerifierMockRecorder {
	return m.recorder
}

// GetCurrentUserGuildMember mocks base method.
func (m *MockMembershipVerifier) GetCurrentUserGuildMember(arg0 context.Context, arg1 *auth.GetCurrentUserGuildMemberInput) (*auth.DiscordGuildMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUserGuildMember", arg0, arg1)
	ret0, _ := ret[0].(*auth.DiscordGuildMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUserGuildMember indicates an expected call of GetCurrentUserGuildMember.
func (mr *MockMembershipVerifierMockRecorder) GetCurrentUserGuildMember(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUserGuildMember", reflect.TypeOf((*MockMembershipVerifier)(nil).GetCurrentUserGuildMember), arg0, arg1)
}
