// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/repositories/dungeons (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go -package=dungeonmock github.com/KirkDiggler/rpg-api/internal/repositories/dungeons Repository
//

// Package dungeonmock is a generated GoMock package.
package dungeonmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dungeons "github.com/KirkDiggler/rpg-api/internal/repositories/dungeons"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, input *dungeons.DeleteInput) (*dungeons.DeleteOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*dungeons.DeleteOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, input *dungeons.GetInput) (*dungeons.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*dungeons.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, input)
}

// GetByEncounterID mocks base method.
func (m *MockRepository) GetByEncounterID(ctx context.Context, input *dungeons.GetByEncounterIDInput) (*dungeons.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEncounterID", ctx, input)
	ret0, _ := ret[0].(*dungeons.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEncounterID indicates an expected call of GetByEncounterID.
func (mr *MockRepositoryMockRecorder) GetByEncounterID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEncounterID", reflect.TypeOf((*MockRepository)(nil).GetByEncounterID), ctx, input)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, input *dungeons.SaveInput) (*dungeons.SaveOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, input)
	ret0, _ := ret[0].(*dungeons.SaveOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, input)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, input *dungeons.UpdateInput) (*dungeons.UpdateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*dungeons.UpdateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, input)
}
