// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock/mock_manager.go -package=sessionv1alpha1mock
//

// Package sessionv1alpha1mock is a generated GoMock package.
package sessionv1alpha1mock

import (
	context "context"
	reflect "reflect"

	session "github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/session"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockManager) Activate(ctx context.Context, in *session.ActivateInput) (*session.ActivateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, in)
	ret0, _ := ret[0].(*session.ActivateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activate indicates an expected call of Activate.
func (mr *MockManagerMockRecorder) Activate(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockManager)(nil).Activate), ctx, in)
}

// Afford mocks base method.
func (m *MockManager) Afford(ctx context.Context, in *session.AffordInput) (*session.AffordOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Afford", ctx, in)
	ret0, _ := ret[0].(*session.AffordOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Afford indicates an expected call of Afford.
func (mr *MockManagerMockRecorder) Afford(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Afford", reflect.TypeOf((*MockManager)(nil).Afford), ctx, in)
}

// Atlas mocks base method.
func (m *MockManager) Atlas(ctx context.Context, in *session.AtlasInput) (*session.Atlas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Atlas", ctx, in)
	ret0, _ := ret[0].(*session.Atlas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Atlas indicates an expected call of Atlas.
func (mr *MockManagerMockRecorder) Atlas(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Atlas", reflect.TypeOf((*MockManager)(nil).Atlas), ctx, in)
}

// Attack mocks base method.
func (m *MockManager) Attack(ctx context.Context, in *session.AttackInput) (*session.AttackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attack", ctx, in)
	ret0, _ := ret[0].(*session.AttackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attack indicates an expected call of Attack.
func (mr *MockManagerMockRecorder) Attack(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attack", reflect.TypeOf((*MockManager)(nil).Attack), ctx, in)
}

// DeathSave mocks base method.
func (m *MockManager) DeathSave(ctx context.Context, in *session.DeathSaveInput) (*session.DeathSaveOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeathSave", ctx, in)
	ret0, _ := ret[0].(*session.DeathSaveOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeathSave indicates an expected call of DeathSave.
func (mr *MockManagerMockRecorder) DeathSave(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeathSave", reflect.TypeOf((*MockManager)(nil).DeathSave), ctx, in)
}

// Dissolve mocks base method.
func (m *MockManager) Dissolve(ctx context.Context, in *session.DissolveInput) (*session.DissolveOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dissolve", ctx, in)
	ret0, _ := ret[0].(*session.DissolveOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dissolve indicates an expected call of Dissolve.
func (mr *MockManagerMockRecorder) Dissolve(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dissolve", reflect.TypeOf((*MockManager)(nil).Dissolve), ctx, in)
}

// Doors mocks base method.
func (m *MockManager) Doors(ctx context.Context, in *session.DoorsInput) (*session.DoorsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Doors", ctx, in)
	ret0, _ := ret[0].(*session.DoorsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Doors indicates an expected call of Doors.
func (mr *MockManagerMockRecorder) Doors(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Doors", reflect.TypeOf((*MockManager)(nil).Doors), ctx, in)
}

// End mocks base method.
func (m *MockManager) End(ctx context.Context, in *session.EndInput) (*session.EndOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "End", ctx, in)
	ret0, _ := ret[0].(*session.EndOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// End indicates an expected call of End.
func (mr *MockManagerMockRecorder) End(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockManager)(nil).End), ctx, in)
}

// EndTurn mocks base method.
func (m *MockManager) EndTurn(ctx context.Context, in *session.EndTurnInput) (*session.EndTurnOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndTurn", ctx, in)
	ret0, _ := ret[0].(*session.EndTurnOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndTurn indicates an expected call of EndTurn.
func (mr *MockManagerMockRecorder) EndTurn(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndTurn", reflect.TypeOf((*MockManager)(nil).EndTurn), ctx, in)
}

// Exit mocks base method.
func (m *MockManager) Exit(ctx context.Context, in *session.ExitInput) (*session.ExitOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exit", ctx, in)
	ret0, _ := ret[0].(*session.ExitOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exit indicates an expected call of Exit.
func (mr *MockManagerMockRecorder) Exit(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exit", reflect.TypeOf((*MockManager)(nil).Exit), ctx, in)
}

// Hold mocks base method.
func (m *MockManager) Hold(ctx context.Context, in *session.HoldInput) (*session.HoldOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hold", ctx, in)
	ret0, _ := ret[0].(*session.HoldOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hold indicates an expected call of Hold.
func (mr *MockManagerMockRecorder) Hold(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hold", reflect.TypeOf((*MockManager)(nil).Hold), ctx, in)
}

// Interact mocks base method.
func (m *MockManager) Interact(ctx context.Context, in *session.InteractInput) (*session.InteractOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Interact", ctx, in)
	ret0, _ := ret[0].(*session.InteractOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Interact indicates an expected call of Interact.
func (mr *MockManagerMockRecorder) Interact(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interact", reflect.TypeOf((*MockManager)(nil).Interact), ctx, in)
}

// Join mocks base method.
func (m *MockManager) Join(ctx context.Context, in *session.JoinInput) (*session.JoinOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, in)
	ret0, _ := ret[0].(*session.JoinOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockManagerMockRecorder) Join(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockManager)(nil).Join), ctx, in)
}

// Loot mocks base method.
func (m *MockManager) Loot(ctx context.Context, in *session.LootInput) (*session.LootOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loot", ctx, in)
	ret0, _ := ret[0].(*session.LootOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Loot indicates an expected call of Loot.
func (mr *MockManagerMockRecorder) Loot(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loot", reflect.TypeOf((*MockManager)(nil).Loot), ctx, in)
}

// Move mocks base method.
func (m *MockManager) Move(ctx context.Context, in *session.MoveInput) (*session.MoveOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, in)
	ret0, _ := ret[0].(*session.MoveOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Move indicates an expected call of Move.
func (mr *MockManagerMockRecorder) Move(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockManager)(nil).Move), ctx, in)
}

// OpenDoor mocks base method.
func (m *MockManager) OpenDoor(ctx context.Context, in *session.OpenDoorInput) (*session.OpenDoorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenDoor", ctx, in)
	ret0, _ := ret[0].(*session.OpenDoorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenDoor indicates an expected call of OpenDoor.
func (mr *MockManagerMockRecorder) OpenDoor(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDoor", reflect.TypeOf((*MockManager)(nil).OpenDoor), ctx, in)
}

// Roster mocks base method.
func (m *MockManager) Roster(ctx context.Context, in *session.RosterInput) (*session.RosterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roster", ctx, in)
	ret0, _ := ret[0].(*session.RosterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Roster indicates an expected call of Roster.
func (mr *MockManagerMockRecorder) Roster(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roster", reflect.TypeOf((*MockManager)(nil).Roster), ctx, in)
}

// Search mocks base method.
func (m *MockManager) Search(ctx context.Context, in *session.SearchInput) (*session.SearchOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, in)
	ret0, _ := ret[0].(*session.SearchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockManagerMockRecorder) Search(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockManager)(nil).Search), ctx, in)
}

// Status mocks base method.
func (m *MockManager) Status(ctx context.Context, in *session.StatusInput) (*session.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, in)
	ret0, _ := ret[0].(*session.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockManagerMockRecorder) Status(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockManager)(nil).Status), ctx, in)
}

// Story mocks base method.
func (m *MockManager) Story(ctx context.Context, in *session.StoryInput) ([]session.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Story", ctx, in)
	ret0, _ := ret[0].([]session.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Story indicates an expected call of Story.
func (mr *MockManagerMockRecorder) Story(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Story", reflect.TypeOf((*MockManager)(nil).Story), ctx, in)
}

// Trade mocks base method.
func (m *MockManager) Trade(ctx context.Context, in *session.TradeInput) (*session.TradeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trade", ctx, in)
	ret0, _ := ret[0].(*session.TradeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trade indicates an expected call of Trade.
func (mr *MockManagerMockRecorder) Trade(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trade", reflect.TypeOf((*MockManager)(nil).Trade), ctx, in)
}

// Turn mocks base method.
func (m *MockManager) Turn(ctx context.Context, in *session.TurnInput) (*session.TurnOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Turn", ctx, in)
	ret0, _ := ret[0].(*session.TurnOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Turn indicates an expected call of Turn.
func (mr *MockManagerMockRecorder) Turn(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Turn", reflect.TypeOf((*MockManager)(nil).Turn), ctx, in)
}

// Unlock mocks base method.
func (m *MockManager) Unlock(ctx context.Context, in *session.UnlockInput) (*session.UnlockOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, in)
	ret0, _ := ret[0].(*session.UnlockOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unlock indicates an expected call of Unlock.
func (mr *MockManagerMockRecorder) Unlock(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockManager)(nil).Unlock), ctx, in)
}

// Unpack mocks base method.
func (m *MockManager) Unpack(ctx context.Context, in *session.UnpackInput) (*session.UnpackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpack", ctx, in)
	ret0, _ := ret[0].(*session.UnpackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unpack indicates an expected call of Unpack.
func (mr *MockManagerMockRecorder) Unpack(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpack", reflect.TypeOf((*MockManager)(nil).Unpack), ctx, in)
}

// View mocks base method.
func (m *MockManager) View(ctx context.Context, in *session.ViewInput) ([]session.Sighting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View", ctx, in)
	ret0, _ := ret[0].([]session.Sighting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// View indicates an expected call of View.
func (mr *MockManagerMockRecorder) View(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockManager)(nil).View), ctx, in)
}

// Where mocks base method.
func (m *MockManager) Where(ctx context.Context, in *session.WhereInput) (*session.WhereOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Where", ctx, in)
	ret0, _ := ret[0].(*session.WhereOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Where indicates an expected call of Where.
func (mr *MockManagerMockRecorder) Where(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockManager)(nil).Where), ctx, in)
}
