// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/orchestrators/character (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_service.go -package=charactermock github.com/KirkDiggler/rpg-api/internal/orchestrators/character Service
//

// Package charactermock is a generated GoMock package.
package charactermock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	character "github.com/KirkDiggler/rpg-api/internal/orchestrators/character"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateDraft mocks base method.
func (m *MockService) CreateDraft(ctx context.Context, input *character.CreateDraftInput) (*character.CreateDraftOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraft", ctx, input)
	ret0, _ := ret[0].(*character.CreateDraftOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraft indicates an expected call of CreateDraft.
func (mr *MockServiceMockRecorder) CreateDraft(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraft", reflect.TypeOf((*MockService)(nil).CreateDraft), ctx, input)
}

// DeleteCharacter mocks base method.
func (m *MockService) DeleteCharacter(ctx context.Context, input *character.DeleteCharacterInput) (*character.DeleteCharacterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCharacter", ctx, input)
	ret0, _ := ret[0].(*character.DeleteCharacterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCharacter indicates an expected call of DeleteCharacter.
func (mr *MockServiceMockRecorder) DeleteCharacter(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCharacter", reflect.TypeOf((*MockService)(nil).DeleteCharacter), ctx, input)
}

// DeleteDraft mocks base method.
func (m *MockService) DeleteDraft(ctx context.Context, input *character.DeleteDraftInput) (*character.DeleteDraftOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDraft", ctx, input)
	ret0, _ := ret[0].(*character.DeleteDraftOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDraft indicates an expected call of DeleteDraft.
func (mr *MockServiceMockRecorder) DeleteDraft(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDraft", reflect.TypeOf((*MockService)(nil).DeleteDraft), ctx, input)
}

// EquipItem mocks base method.
func (m *MockService) EquipItem(ctx context.Context, input *character.EquipItemInput) (*character.EquipItemOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EquipItem", ctx, input)
	ret0, _ := ret[0].(*character.EquipItemOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EquipItem indicates an expected call of EquipItem.
func (mr *MockServiceMockRecorder) EquipItem(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EquipItem", reflect.TypeOf((*MockService)(nil).EquipItem), ctx, input)
}

// FinalizeDraft mocks base method.
func (m *MockService) FinalizeDraft(ctx context.Context, input *character.FinalizeDraftInput) (*character.FinalizeDraftOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeDraft", ctx, input)
	ret0, _ := ret[0].(*character.FinalizeDraftOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeDraft indicates an expected call of FinalizeDraft.
func (mr *MockServiceMockRecorder) FinalizeDraft(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeDraft", reflect.TypeOf((*MockService)(nil).FinalizeDraft), ctx, input)
}

// GetCharacter mocks base method.
func (m *MockService) GetCharacter(ctx context.Context, input *character.GetCharacterInput) (*character.GetCharacterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacter", ctx, input)
	ret0, _ := ret[0].(*character.GetCharacterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacter indicates an expected call of GetCharacter.
func (mr *MockServiceMockRecorder) GetCharacter(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacter", reflect.TypeOf((*MockService)(nil).GetCharacter), ctx, input)
}

// GetDraft mocks base method.
func (m *MockService) GetDraft(ctx context.Context, input *character.GetDraftInput) (*character.GetDraftOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDraft", ctx, input)
	ret0, _ := ret[0].(*character.GetDraftOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDraft indicates an expected call of GetDraft.
func (mr *MockServiceMockRecorder) GetDraft(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDraft", reflect.TypeOf((*MockService)(nil).GetDraft), ctx, input)
}

// GetRequirements mocks base method.
func (m *MockService) GetRequirements(ctx context.Context, input *character.GetRequirementsInput) (*character.GetRequirementsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequirements", ctx, input)
	ret0, _ := ret[0].(*character.GetRequirementsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequirements indicates an expected call of GetRequirements.
func (mr *MockServiceMockRecorder) GetRequirements(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequirements", reflect.TypeOf((*MockService)(nil).GetRequirements), ctx, input)
}

// ListBackgrounds mocks base method.
func (m *MockService) ListBackgrounds(ctx context.Context, input *character.ListBackgroundsInput) (*character.ListBackgroundsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBackgrounds", ctx, input)
	ret0, _ := ret[0].(*character.ListBackgroundsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBackgrounds indicates an expected call of ListBackgrounds.
func (mr *MockServiceMockRecorder) ListBackgrounds(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBackgrounds", reflect.TypeOf((*MockService)(nil).ListBackgrounds), ctx, input)
}

// ListCharacters mocks base method.
func (m *MockService) ListCharacters(ctx context.Context, input *character.ListCharactersInput) (*character.ListCharactersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCharacters", ctx, input)
	ret0, _ := ret[0].(*character.ListCharactersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCharacters indicates an expected call of ListCharacters.
func (mr *MockServiceMockRecorder) ListCharacters(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCharacters", reflect.TypeOf((*MockService)(nil).ListCharacters), ctx, input)
}

// ListClasses mocks base method.
func (m *MockService) ListClasses(ctx context.Context, input *character.ListClassesInput) (*character.ListClassesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClasses", ctx, input)
	ret0, _ := ret[0].(*character.ListClassesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClasses indicates an expected call of ListClasses.
func (mr *MockServiceMockRecorder) ListClasses(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClasses", reflect.TypeOf((*MockService)(nil).ListClasses), ctx, input)
}

// ListDrafts mocks base method.
func (m *MockService) ListDrafts(ctx context.Context, input *character.ListDraftsInput) (*character.ListDraftsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDrafts", ctx, input)
	ret0, _ := ret[0].(*character.ListDraftsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDrafts indicates an expected call of ListDrafts.
func (mr *MockServiceMockRecorder) ListDrafts(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDrafts", reflect.TypeOf((*MockService)(nil).ListDrafts), ctx, input)
}

// ListEquipmentByType mocks base method.
func (m *MockService) ListEquipmentByType(ctx context.Context, input *character.ListEquipmentByTypeInput) (*character.ListEquipmentByTypeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEquipmentByType", ctx, input)
	ret0, _ := ret[0].(*character.ListEquipmentByTypeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEquipmentByType indicates an expected call of ListEquipmentByType.
func (mr *MockServiceMockRecorder) ListEquipmentByType(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEquipmentByType", reflect.TypeOf((*MockService)(nil).ListEquipmentByType), ctx, input)
}

// ListRaces mocks base method.
func (m *MockService) ListRaces(ctx context.Context, input *character.ListRacesInput) (*character.ListRacesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRaces", ctx, input)
	ret0, _ := ret[0].(*character.ListRacesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRaces indicates an expected call of ListRaces.
func (mr *MockServiceMockRecorder) ListRaces(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRaces", reflect.TypeOf((*MockService)(nil).ListRaces), ctx, input)
}

// ListSpellsByLevel mocks base method.
func (m *MockService) ListSpellsByLevel(ctx context.Context, input *character.ListSpellsByLevelInput) (*character.ListSpellsByLevelOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpellsByLevel", ctx, input)
	ret0, _ := ret[0].(*character.ListSpellsByLevelOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpellsByLevel indicates an expected call of ListSpellsByLevel.
func (mr *MockServiceMockRecorder) ListSpellsByLevel(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpellsByLevel", reflect.TypeOf((*MockService)(nil).ListSpellsByLevel), ctx, input)
}

// RollAbilityScores mocks base method.
func (m *MockService) RollAbilityScores(ctx context.Context, input *character.RollAbilityScoresInput) (*character.RollAbilityScoresOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollAbilityScores", ctx, input)
	ret0, _ := ret[0].(*character.RollAbilityScoresOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollAbilityScores indicates an expected call of RollAbilityScores.
func (mr *MockServiceMockRecorder) RollAbilityScores(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollAbilityScores", reflect.TypeOf((*MockService)(nil).RollAbilityScores), ctx, input)
}

// SetAbilityScores mocks base method.
func (m *MockService) SetAbilityScores(ctx context.Context, input *character.SetAbilityScoresInput) (*character.SetAbilityScoresOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAbilityScores", ctx, input)
	ret0, _ := ret[0].(*character.SetAbilityScoresOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAbilityScores indicates an expected call of SetAbilityScores.
func (mr *MockServiceMockRecorder) SetAbilityScores(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAbilityScores", reflect.TypeOf((*MockService)(nil).SetAbilityScores), ctx, input)
}

// SetAbilityScoresFromRolls mocks base method.
func (m *MockService) SetAbilityScoresFromRolls(ctx context.Context, input *character.SetAbilityScoresFromRollsInput) (*character.SetAbilityScoresFromRollsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAbilityScoresFromRolls", ctx, input)
	ret0, _ := ret[0].(*character.SetAbilityScoresFromRollsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAbilityScoresFromRolls indicates an expected call of SetAbilityScoresFromRolls.
func (mr *MockServiceMockRecorder) SetAbilityScoresFromRolls(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAbilityScoresFromRolls", reflect.TypeOf((*MockService)(nil).SetAbilityScoresFromRolls), ctx, input)
}

// SetAppearance mocks base method.
func (m *MockService) SetAppearance(ctx context.Context, input *character.SetAppearanceInput) (*character.SetAppearanceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAppearance", ctx, input)
	ret0, _ := ret[0].(*character.SetAppearanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAppearance indicates an expected call of SetAppearance.
func (mr *MockServiceMockRecorder) SetAppearance(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppearance", reflect.TypeOf((*MockService)(nil).SetAppearance), ctx, input)
}

// SetBackground mocks base method.
func (m *MockService) SetBackground(ctx context.Context, input *character.SetBackgroundInput) (*character.SetBackgroundOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBackground", ctx, input)
	ret0, _ := ret[0].(*character.SetBackgroundOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBackground indicates an expected call of SetBackground.
func (mr *MockServiceMockRecorder) SetBackground(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBackground", reflect.TypeOf((*MockService)(nil).SetBackground), ctx, input)
}

// SetClass mocks base method.
func (m *MockService) SetClass(ctx context.Context, input *character.SetClassInput) (*character.SetClassOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClass", ctx, input)
	ret0, _ := ret[0].(*character.SetClassOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetClass indicates an expected call of SetClass.
func (mr *MockServiceMockRecorder) SetClass(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClass", reflect.TypeOf((*MockService)(nil).SetClass), ctx, input)
}

// SetName mocks base method.
func (m *MockService) SetName(ctx context.Context, input *character.SetNameInput) (*character.SetNameOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetName", ctx, input)
	ret0, _ := ret[0].(*character.SetNameOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetName indicates an expected call of SetName.
func (mr *MockServiceMockRecorder) SetName(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockService)(nil).SetName), ctx, input)
}

// SetRace mocks base method.
func (m *MockService) SetRace(ctx context.Context, input *character.SetRaceInput) (*character.SetRaceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRace", ctx, input)
	ret0, _ := ret[0].(*character.SetRaceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRace indicates an expected call of SetRace.
func (mr *MockServiceMockRecorder) SetRace(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRace", reflect.TypeOf((*MockService)(nil).SetRace), ctx, input)
}

// UnequipItem mocks base method.
func (m *MockService) UnequipItem(ctx context.Context, input *character.UnequipItemInput) (*character.UnequipItemOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnequipItem", ctx, input)
	ret0, _ := ret[0].(*character.UnequipItemOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnequipItem indicates an expected call of UnequipItem.
func (mr *MockServiceMockRecorder) UnequipItem(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnequipItem", reflect.TypeOf((*MockService)(nil).UnequipItem), ctx, input)
}

// ValidateDraft mocks base method.
func (m *MockService) ValidateDraft(ctx context.Context, input *character.ValidateDraftInput) (*character.ValidateDraftOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDraft", ctx, input)
	ret0, _ := ret[0].(*character.ValidateDraftOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateDraft indicates an expected call of ValidateDraft.
func (mr *MockServiceMockRecorder) ValidateDraft(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDraft", reflect.TypeOf((*MockService)(nil).ValidateDraft), ctx, input)
}
