version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  default: none
  enable:
    # Default linters (all good to keep)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional valuable linters
    - bodyclose      # Check HTTP response body is closed
    - copyloopvar    # Detect places where loop variables are copied
    - dupl           # Find duplicate code
    - goconst        # Find repeated strings that could be constants
    - gocritic       # Comprehensive checks for bugs, performance, style
    - gocyclo        # Check cyclomatic complexity
    - goprintffuncname # Printf-like functions should end with 'f'
    - gosec          # Security checks
    - lll            # Line length limit
    - misspell       # Find misspelled words
    - nakedret       # Find naked returns
    - noctx          # Find missing context.Context
    - prealloc       # Find slices that could be preallocated
    - revive         # Comprehensive linter, replaces golint
    - rowserrcheck   # Check sql.Rows.Err
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused parameters
    - whitespace     # Check unnecessary newlines

settings:
  dupl:
    threshold: 100
  
  errcheck:
    check-type-assertions: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - whyNoLint
  
  gocyclo:
    min-complexity: 15
  
  govet:
    enable:
      - shadow
  
  lll:
    line-length: 120
    tab-width: 4
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-dirs:
    - gen/go
    - internal/services/character/mock
    - ".*mock.*"
    
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - goconst
        - gosec
        - gocyclo
    
    # Allow longer lines in generate directives
    - source: "^//go:generate "
      linters:
        - lll
    
    # Allow longer lines in proto file paths
    - source: "github.com/KirkDiggler/rpg-api/gen/go/"
      linters:
        - lll
  
  max-issues-per-linter: 0
  max-same-issues: 0
