// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/dungeons (interfaces: Registry)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_registry.go -package=dungeonsmock github.com/KirkDiggler/rpg-api/internal/dungeons Registry
//

// Package dungeonsmock is a generated GoMock package.
package dungeonsmock

import (
	context "context"
	reflect "reflect"

	dungeons "github.com/KirkDiggler/rpg-api/internal/dungeons"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRegistry) Get(ctx context.Context, key string) (*dungeons.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*dungeons.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRegistryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistry)(nil).Get), ctx, key)
}

// List mocks base method.
func (m *MockRegistry) List(ctx context.Context) ([]dungeons.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]dungeons.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRegistryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRegistry)(nil).List), ctx)
}

// Put mocks base method.
func (m *MockRegistry) Put(ctx context.Context, in *dungeons.PutInput) (*dungeons.PutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, in)
	ret0, _ := ret[0].(*dungeons.PutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRegistryMockRecorder) Put(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRegistry)(nil).Put), ctx, in)
}
