package dungeon

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/KirkDiggler/rpg-api/internal/components/dungeon/presentation"
)

// LayoutGenerator creates room layouts and connections
type LayoutGenerator interface {
	Generate(ctx context.Context, input *LayoutInput) (*LayoutOutput, error)
}

// LayoutInput defines parameters for layout generation
type LayoutInput struct {
	Length     int
	LayoutType LayoutType
	Seed       int64
}

// LayoutOutput contains the generated room layout
type LayoutOutput struct {
	RoomSlots   []RoomSlot
	Connections []*LayoutConnection
	StartRoom   int // index
	BossRoom    int // index
}

// LayoutConnection defines a connection between two room slots by index
type LayoutConnection struct {
	FromRoom     int // index into RoomSlots
	ToRoom       int // index into RoomSlots
	Type         ConnectionType
	IsMainPath   bool
	PhysicalHint string
}

// RoomSlot represents a placeholder for a room to be generated
type RoomSlot struct {
	ID       string
	RoomType RoomType // typed room type for pattern selection
}

// ShapeGenerator creates room geometry
type ShapeGenerator interface {
	Generate(ctx context.Context, input *ShapeInput) (*ShapeOutput, error)
}

// ShapeInput defines parameters for shape generation
type ShapeInput struct {
	Size     RoomSize
	Style    ShapeStyle
	RoomType RoomType // Used for shape selection based on room purpose
	Seed     int64
}

// ShapeOutput contains the generated shape
type ShapeOutput struct {
	Shape          *Shape
	PerimeterWalls []WallSegment
}

// PerimeterUpdater regenerates perimeter walls with door openings
type PerimeterUpdater interface {
	UpdatePerimeter(input *UpdatePerimeterInput) *UpdatePerimeterOutput
}

// UpdatePerimeterInput contains parameters for updating perimeter walls
type UpdatePerimeterInput struct {
	Shape       *Shape
	Connections []*RoomConnection
}

// UpdatePerimeterOutput contains the updated perimeter walls
type UpdatePerimeterOutput struct {
	Walls         []WallSegment
	DoorPositions []Position
}

// FeatureGenerator places obstacles and spawn zones
type FeatureGenerator interface {
	Generate(ctx context.Context, input *FeatureInput) (*FeatureOutput, error)
}

// FeatureInput defines parameters for feature placement
type FeatureInput struct {
	Shape    *Shape
	Rules    FeatureRules
	Tables   *ThemeTables // Pattern selection tables
	RoomType RoomType     // affects pattern and spawn zone selection
	Seed     int64
}

// FeatureOutput contains the generated features
type FeatureOutput struct {
	Features *FeatureLayout
	Walls    []WallSegment // Internal walls generated by patterns
	Zones    []Zone        // Spawn zones (separate from Features for clarity)
}

// EncounterGenerator creates monster encounters for rooms
type EncounterGenerator interface {
	Generate(ctx context.Context, input *EncounterInput) (*EncounterOutput, error)
}

// EncounterInput defines parameters for encounter generation
type EncounterInput struct {
	MonsterPool []MonsterRef
	BossPool    []MonsterRef
	CRBudget    float64
	IsBossRoom  bool
	Seed        int64
}

// EncounterOutput contains the generated encounter
type EncounterOutput struct {
	Encounter *Encounter
}

// BudgetAllocator allocates CR budget across rooms
type BudgetAllocator interface {
	AllocateBudget(input *BudgetInput) *BudgetOutput
}

// BudgetInput defines parameters for budget allocation
type BudgetInput struct {
	TotalRooms int
	PartySize  int
	TargetCR   int
}

// BudgetOutput contains the allocated budgets
type BudgetOutput struct {
	RoomBudgets []float64
}

// GeneratorConfig contains dependencies for the generator
type GeneratorConfig struct {
	LayoutGen        LayoutGenerator
	ShapeGen         ShapeGenerator
	FeatureGen       FeatureGenerator
	EncounterGen     EncounterGenerator
	BudgetAllocator  BudgetAllocator
	PerimeterUpdater PerimeterUpdater
}

// Generator orchestrates all layers of dungeon generation
type Generator struct {
	layoutGen        LayoutGenerator
	shapeGen         ShapeGenerator
	featureGen       FeatureGenerator
	encounterGen     EncounterGenerator
	budgetAllocator  BudgetAllocator
	perimeterUpdater PerimeterUpdater
	directionAdapter *DirectionAdapter
}

// NewGenerator creates a new dungeon generator with injected dependencies
func NewGenerator(cfg *GeneratorConfig) *Generator {
	return &Generator{
		layoutGen:        cfg.LayoutGen,
		shapeGen:         cfg.ShapeGen,
		featureGen:       cfg.FeatureGen,
		encounterGen:     cfg.EncounterGen,
		budgetAllocator:  cfg.BudgetAllocator,
		perimeterUpdater: cfg.PerimeterUpdater,
		directionAdapter: NewDirectionAdapter(),
	}
}

// Generate creates a complete dungeon from the input parameters
func (g *Generator) Generate(ctx context.Context, input *GenerateInput) (*GenerateOutput, error) {
	if input == nil {
		return nil, fmt.Errorf("input is required")
	}

	if input.Length <= 0 {
		return nil, fmt.Errorf("length must be greater than 0")
	}

	if input.PartySize <= 0 {
		return nil, fmt.Errorf("party size must be greater than 0")
	}

	if input.TargetCR <= 0 {
		return nil, fmt.Errorf("target CR must be greater than 0")
	}

	// Generate or use provided seed
	seed := input.Seed
	if seed == 0 {
		seed = time.Now().UnixNano()
	}

	// Step 1: Allocate CR budget across rooms
	budgetOutput := g.budgetAllocator.AllocateBudget(&BudgetInput{
		TotalRooms: input.Length,
		PartySize:  input.PartySize,
		TargetCR:   input.TargetCR,
	})

	// Step 2: Generate layout (rooms and connections)
	layoutOutput, err := g.layoutGen.Generate(ctx, &LayoutInput{
		Length:     input.Length,
		LayoutType: input.Layout,
		Seed:       seed,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate layout: %w", err)
	}

	// Step 3: Generate each room (shape, features, encounter)
	rooms := make([]*Room, len(layoutOutput.RoomSlots))
	for i, slot := range layoutOutput.RoomSlots {
		room, err := g.generateRoom(ctx, &generateRoomInput{
			slot:       slot,
			size:       input.Size,
			theme:      input.Theme,
			crBudget:   budgetOutput.RoomBudgets[i],
			isBossRoom: i == layoutOutput.BossRoom,
			seed:       seed + int64(i),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to generate room %d: %w", i, err)
		}
		rooms[i] = room
	}

	// Step 4: Update connections with actual room IDs and assign directions
	connections := make([]*RoomConnection, len(layoutOutput.Connections))
	for i, conn := range layoutOutput.Connections {
		// Handle outside connection (FromRoom = -1 means entrance from outside dungeon)
		fromRoomID := ""
		if conn.FromRoom >= 0 {
			fromRoomID = rooms[conn.FromRoom].ID
		}
		// ToRoom should always be valid (>= 0)
		toRoomID := rooms[conn.ToRoom].ID

		connections[i] = &RoomConnection{
			FromRoom:     fromRoomID,
			ToRoom:       toRoomID,
			Type:         conn.Type,
			IsMainPath:   conn.IsMainPath,
			PhysicalHint: conn.PhysicalHint,
		}
	}

	// Step 4b: Derive cardinal directions from layout topology
	roomOrder := make([]string, len(rooms))
	for i, room := range rooms {
		roomOrder[i] = room.ID
	}
	dirAdapter := g.directionAdapter
	if dirAdapter == nil {
		dirAdapter = &DirectionAdapter{}
	}
	dirOutput := dirAdapter.AssignDirections(&DirectionAdapterInput{
		Connections: connections,
		Layout:      input.Layout,
		RoomOrder:   roomOrder,
	})
	connections = dirOutput.Connections

	// Step 4c: Update perimeter walls with door openings now that connections are known
	if g.perimeterUpdater != nil {
		g.updateRoomPerimeters(rooms, connections)
	}

	// Step 5: Apply presentation layer to obscure main path
	connections = g.applyPresentation(connections, input.Theme, seed)

	// Step 6: Assemble final dungeon
	dungeon := &Dungeon{
		ID:          uuid.New().String(),
		Theme:       input.Theme,
		Rooms:       rooms,
		Connections: connections,
		StartRoom:   rooms[layoutOutput.StartRoom].ID,
		BossRoom:    rooms[layoutOutput.BossRoom].ID,
	}

	return &GenerateOutput{
		Dungeon: dungeon,
		Seed:    seed,
	}, nil
}

// generateRoomInput contains all parameters needed to generate a single room
type generateRoomInput struct {
	slot       RoomSlot
	size       RoomSize
	theme      Theme
	crBudget   float64
	isBossRoom bool
	seed       int64
}

// generateRoom creates a single room with shape, features, and encounter
func (g *Generator) generateRoom(ctx context.Context, input *generateRoomInput) (*Room, error) {
	// Generate shape
	shapeOutput, err := g.shapeGen.Generate(ctx, &ShapeInput{
		Size:     input.size,
		Style:    input.theme.ShapeStyle,
		RoomType: input.slot.RoomType,
		Seed:     input.seed,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate shape: %w", err)
	}

	// Generate features
	featureOutput, err := g.featureGen.Generate(ctx, &FeatureInput{
		Shape:    shapeOutput.Shape,
		Rules:    input.theme.Features,
		Tables:   input.theme.Tables,
		RoomType: input.slot.RoomType,
		Seed:     input.seed + 1,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate features: %w", err)
	}

	// Generate encounter
	encounterOutput, err := g.encounterGen.Generate(ctx, &EncounterInput{
		MonsterPool: input.theme.MonsterPool,
		BossPool:    input.theme.BossPool,
		CRBudget:    input.crBudget,
		IsBossRoom:  input.isBossRoom,
		Seed:        input.seed + 2,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate encounter: %w", err)
	}

	// Convert spawn zones to pointers
	spawnZones := make([]*Zone, len(featureOutput.Zones))
	for i := range featureOutput.Zones {
		zone := featureOutput.Zones[i]
		spawnZones[i] = &zone
	}

	// Combine perimeter walls and internal walls
	walls := make([]WallSegment, 0, len(shapeOutput.PerimeterWalls)+len(featureOutput.Walls))
	walls = append(walls, shapeOutput.PerimeterWalls...)
	walls = append(walls, featureOutput.Walls...)

	return &Room{
		ID:         input.slot.ID,
		Shape:      shapeOutput.Shape,
		Features:   featureOutput.Features,
		SpawnZones: spawnZones,
		Walls:      walls,
		Encounter:  encounterOutput.Encounter,
	}, nil
}

// applyPresentation applies presentation layer transformations to obscure the main path
func (g *Generator) applyPresentation(connections []*RoomConnection, theme Theme, seed int64) []*RoomConnection {
	// Convert to presentation types
	presConnections := make([]*presentation.RoomConnection, len(connections))
	for i, conn := range connections {
		presConnections[i] = &presentation.RoomConnection{
			FromRoom:     conn.FromRoom,
			ToRoom:       conn.ToRoom,
			Type:         presentation.ConnectionType(conn.Type),
			IsMainPath:   conn.IsMainPath,
			Direction:    presentation.Direction(conn.Direction),
			PhysicalHint: conn.PhysicalHint,
		}
	}

	// Generate themed physical hints for connections
	hintGen := presentation.NewHintGenerator()
	hintOutput := hintGen.GenerateHints(&presentation.HintInput{
		Connections: presConnections,
		Theme:       presentation.Theme{ID: theme.ID},
		Seed:        seed + 1000, // Offset seed to avoid correlation with other generators
	})

	// Shuffle connection order to prevent "main path first" pattern
	shuffled := presentation.ShuffleConnections(hintOutput.Connections, seed+2000)

	// Convert back to dungeon types
	result := make([]*RoomConnection, len(shuffled))
	for i, conn := range shuffled {
		result[i] = &RoomConnection{
			FromRoom:     conn.FromRoom,
			ToRoom:       conn.ToRoom,
			Type:         ConnectionType(conn.Type),
			IsMainPath:   conn.IsMainPath,
			Direction:    Direction(conn.Direction),
			PhysicalHint: conn.PhysicalHint,
		}
	}

	return result
}

// updateRoomPerimeters regenerates perimeter walls with door openings for all rooms
func (g *Generator) updateRoomPerimeters(rooms []*Room, connections []*RoomConnection) {
	// Build room ID to room pointer map for quick lookup
	roomMap := make(map[string]*Room)
	for _, room := range rooms {
		roomMap[room.ID] = room
	}

	// For each room, find its connections and update perimeter walls
	for _, room := range rooms {
		// Find all connections for this room
		roomConnections := g.findConnectionsForRoom(room.ID, connections)
		if len(roomConnections) == 0 {
			continue // No connections, keep original solid walls
		}

		// Generate new perimeter walls with door openings
		output := g.perimeterUpdater.UpdatePerimeter(&UpdatePerimeterInput{
			Shape:       room.Shape,
			Connections: roomConnections,
		})

		// Replace perimeter walls in room's wall list
		// Keep internal walls (non-perimeter), replace perimeter walls
		room.Walls = g.replacePerimeterWalls(room.Walls, output.Walls)
	}
}

// findConnectionsForRoom returns all connections involving the given room
// Connections are normalized so Direction/PhysicalHint are from the room's perspective
func (g *Generator) findConnectionsForRoom(roomID string, connections []*RoomConnection) []*RoomConnection {
	var result []*RoomConnection
	for _, conn := range connections {
		if conn.FromRoom == roomID {
			// Connection is from this room - use as-is, but ensure PhysicalHint matches Direction
			normalized := &RoomConnection{
				FromRoom:     conn.FromRoom,
				ToRoom:       conn.ToRoom,
				Type:         conn.Type,
				IsMainPath:   conn.IsMainPath,
				Direction:    conn.Direction,
				PhysicalHint: string(conn.Direction), // Use direction as physical hint for perimeter matching
			}
			result = append(result, normalized)
		} else if conn.ToRoom == roomID {
			// Connection is to this room
			if conn.FromRoom == "" {
				// Outside connection - PhysicalHint specifies wall directly, don't flip
				normalized := &RoomConnection{
					FromRoom:     conn.ToRoom,
					ToRoom:       conn.FromRoom,
					Type:         conn.Type,
					IsMainPath:   conn.IsMainPath,
					Direction:    conn.Direction,
					PhysicalHint: string(conn.Direction), // Use direction as-is for entrance wall
				}
				result = append(result, normalized)
			} else {
				// Normal room-to-room connection - flip the direction
				oppositeDir := g.getOppositeDirection(conn.Direction)
				normalized := &RoomConnection{
					FromRoom:     conn.ToRoom,
					ToRoom:       conn.FromRoom,
					Type:         conn.Type,
					IsMainPath:   conn.IsMainPath,
					Direction:    oppositeDir,
					PhysicalHint: string(oppositeDir), // Use opposite direction as physical hint
				}
				result = append(result, normalized)
			}
		}
	}
	return result
}

// getOppositeDirection returns the opposite cardinal direction
func (g *Generator) getOppositeDirection(dir Direction) Direction {
	switch dir {
	case DirectionNorth:
		return DirectionSouth
	case DirectionSouth:
		return DirectionNorth
	case DirectionEast:
		return DirectionWest
	case DirectionWest:
		return DirectionEast
	default:
		return dir
	}
}

// replacePerimeterWalls keeps internal walls and replaces perimeter walls
func (g *Generator) replacePerimeterWalls(existingWalls, newPerimeterWalls []WallSegment) []WallSegment {
	// Keep only non-perimeter walls (internal walls)
	var internalWalls []WallSegment
	for _, wall := range existingWalls {
		if !isPerimeterWall(wall.ID) {
			internalWalls = append(internalWalls, wall)
		}
	}

	// Combine new perimeter walls with existing internal walls
	result := make([]WallSegment, 0, len(newPerimeterWalls)+len(internalWalls))
	result = append(result, newPerimeterWalls...)
	result = append(result, internalWalls...)
	return result
}

// isPerimeterWall checks if a wall ID indicates it's a perimeter wall
func isPerimeterWall(id string) bool {
	return len(id) > 10 && id[:10] == "perimeter_"
}
