// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/orchestrators/lobby (interfaces: SessionManager)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_session_manager.go -package=lobbymock github.com/KirkDiggler/rpg-api/internal/orchestrators/lobby SessionManager
//

// Package lobbymock is a generated GoMock package.
package lobbymock

import (
	context "context"
	reflect "reflect"

	session "github.com/KirkDiggler/rpg-toolkit/rulebooks/dnd5e/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// End mocks base method.
func (m *MockSessionManager) End(arg0 context.Context, arg1 *session.EndInput) (*session.EndOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "End", arg0, arg1)
	ret0, _ := ret[0].(*session.EndOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// End indicates an expected call of End.
func (mr *MockSessionManagerMockRecorder) End(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSessionManager)(nil).End), arg0, arg1)
}

// Launch mocks base method.
func (m *MockSessionManager) Launch(arg0 context.Context, arg1 *session.LaunchInput) (*session.LaunchOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch", arg0, arg1)
	ret0, _ := ret[0].(*session.LaunchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Launch indicates an expected call of Launch.
func (mr *MockSessionManagerMockRecorder) Launch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockSessionManager)(nil).Launch), arg0, arg1)
}

// PlaceNPC mocks base method.
func (m *MockSessionManager) PlaceNPC(arg0 context.Context, arg1 *session.PlaceNPCInput) (*session.PlaceNPCOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceNPC", arg0, arg1)
	ret0, _ := ret[0].(*session.PlaceNPCOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceNPC indicates an expected call of PlaceNPC.
func (mr *MockSessionManagerMockRecorder) PlaceNPC(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceNPC", reflect.TypeOf((*MockSessionManager)(nil).PlaceNPC), arg0, arg1)
}

// Status mocks base method.
func (m *MockSessionManager) Status(arg0 context.Context, arg1 *session.StatusInput) (*session.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0, arg1)
	ret0, _ := ret[0].(*session.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSessionManagerMockRecorder) Status(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSessionManager)(nil).Status), arg0, arg1)
}
