// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/orchestrators/authoring (interfaces: Compiler)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_compiler.go -package=authoringmock github.com/KirkDiggler/rpg-api/internal/orchestrators/authoring Compiler
//

// Package authoringmock is a generated GoMock package.
package authoringmock

import (
	context "context"
	reflect "reflect"

	authoring "github.com/KirkDiggler/rpg-api/internal/orchestrators/authoring"
	gomock "go.uber.org/mock/gomock"
)

// MockCompiler is a mock of Compiler interface.
type MockCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder struct {
	mock *MockCompiler
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler(ctrl *gomock.Controller) *MockCompiler {
	mock := &MockCompiler{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler) EXPECT() *MockCompilerMockRecorder {
	return m.recorder
}

// CompileDungeon mocks base method.
func (m *MockCompiler) CompileDungeon(ctx context.Context, in *authoring.CompileDungeonInput) (*authoring.CompileDungeonOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompileDungeon", ctx, in)
	ret0, _ := ret[0].(*authoring.CompileDungeonOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompileDungeon indicates an expected call of CompileDungeon.
func (mr *MockCompilerMockRecorder) CompileDungeon(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompileDungeon", reflect.TypeOf((*MockCompiler)(nil).CompileDungeon), ctx, in)
}
