// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/services/sandboxroom (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_service.go -package=sandboxroommock github.com/KirkDiggler/rpg-api/internal/services/sandboxroom Service
//

// Package sandboxroommock is a generated GoMock package.
package sandboxroommock

import (
	context "context"
	reflect "reflect"

	sandboxroom "github.com/KirkDiggler/rpg-api/internal/services/sandboxroom"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BuildStaticRoom mocks base method.
func (m *MockService) BuildStaticRoom(ctx context.Context, input *sandboxroom.BuildStaticRoomInput) (*sandboxroom.BuildStaticRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildStaticRoom", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.BuildStaticRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildStaticRoom indicates an expected call of BuildStaticRoom.
func (mr *MockServiceMockRecorder) BuildStaticRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildStaticRoom", reflect.TypeOf((*MockService)(nil).BuildStaticRoom), ctx, input)
}

// CalculateDistance mocks base method.
func (m *MockService) CalculateDistance(ctx context.Context, input *sandboxroom.CalculateDistanceInput) (*sandboxroom.CalculateDistanceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateDistance", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.CalculateDistanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateDistance indicates an expected call of CalculateDistance.
func (mr *MockServiceMockRecorder) CalculateDistance(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateDistance", reflect.TypeOf((*MockService)(nil).CalculateDistance), ctx, input)
}

// CheckLineOfSight mocks base method.
func (m *MockService) CheckLineOfSight(ctx context.Context, input *sandboxroom.CheckLineOfSightInput) (*sandboxroom.CheckLineOfSightOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLineOfSight", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.CheckLineOfSightOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLineOfSight indicates an expected call of CheckLineOfSight.
func (mr *MockServiceMockRecorder) CheckLineOfSight(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLineOfSight", reflect.TypeOf((*MockService)(nil).CheckLineOfSight), ctx, input)
}

// DeleteRoom mocks base method.
func (m *MockService) DeleteRoom(ctx context.Context, input *sandboxroom.DeleteRoomInput) (*sandboxroom.DeleteRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.DeleteRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockServiceMockRecorder) DeleteRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockService)(nil).DeleteRoom), ctx, input)
}

// FindPath mocks base method.
func (m *MockService) FindPath(ctx context.Context, input *sandboxroom.FindPathInput) (*sandboxroom.FindPathOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPath", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.FindPathOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPath indicates an expected call of FindPath.
func (mr *MockServiceMockRecorder) FindPath(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPath", reflect.TypeOf((*MockService)(nil).FindPath), ctx, input)
}

// GenerateRoom mocks base method.
func (m *MockService) GenerateRoom(ctx context.Context, input *sandboxroom.GenerateRoomInput) (*sandboxroom.GenerateRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRoom", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.GenerateRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRoom indicates an expected call of GenerateRoom.
func (mr *MockServiceMockRecorder) GenerateRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRoom", reflect.TypeOf((*MockService)(nil).GenerateRoom), ctx, input)
}

// GetEntitiesInRoom mocks base method.
func (m *MockService) GetEntitiesInRoom(ctx context.Context, input *sandboxroom.GetEntitiesInRoomInput) (*sandboxroom.GetEntitiesInRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitiesInRoom", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.GetEntitiesInRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntitiesInRoom indicates an expected call of GetEntitiesInRoom.
func (mr *MockServiceMockRecorder) GetEntitiesInRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitiesInRoom", reflect.TypeOf((*MockService)(nil).GetEntitiesInRoom), ctx, input)
}

// GetPositionsInRange mocks base method.
func (m *MockService) GetPositionsInRange(ctx context.Context, input *sandboxroom.GetPositionsInRangeInput) (*sandboxroom.GetPositionsInRangeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPositionsInRange", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.GetPositionsInRangeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPositionsInRange indicates an expected call of GetPositionsInRange.
func (mr *MockServiceMockRecorder) GetPositionsInRange(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPositionsInRange", reflect.TypeOf((*MockService)(nil).GetPositionsInRange), ctx, input)
}

// GetRoom mocks base method.
func (m *MockService) GetRoom(ctx context.Context, input *sandboxroom.GetRoomInput) (*sandboxroom.GetRoomOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.GetRoomOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockServiceMockRecorder) GetRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockService)(nil).GetRoom), ctx, input)
}

// ListRooms mocks base method.
func (m *MockService) ListRooms(ctx context.Context, input *sandboxroom.ListRoomsInput) (*sandboxroom.ListRoomsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.ListRoomsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockServiceMockRecorder) ListRooms(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockService)(nil).ListRooms), ctx, input)
}

// MoveEntity mocks base method.
func (m *MockService) MoveEntity(ctx context.Context, input *sandboxroom.MoveEntityInput) (*sandboxroom.MoveEntityOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveEntity", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.MoveEntityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveEntity indicates an expected call of MoveEntity.
func (mr *MockServiceMockRecorder) MoveEntity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveEntity", reflect.TypeOf((*MockService)(nil).MoveEntity), ctx, input)
}

// PlaceEntity mocks base method.
func (m *MockService) PlaceEntity(ctx context.Context, input *sandboxroom.PlaceEntityInput) (*sandboxroom.PlaceEntityOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceEntity", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.PlaceEntityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceEntity indicates an expected call of PlaceEntity.
func (mr *MockServiceMockRecorder) PlaceEntity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceEntity", reflect.TypeOf((*MockService)(nil).PlaceEntity), ctx, input)
}

// RemoveEntity mocks base method.
func (m *MockService) RemoveEntity(ctx context.Context, input *sandboxroom.RemoveEntityInput) (*sandboxroom.RemoveEntityOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEntity", ctx, input)
	ret0, _ := ret[0].(*sandboxroom.RemoveEntityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveEntity indicates an expected call of RemoveEntity.
func (mr *MockServiceMockRecorder) RemoveEntity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntity", reflect.TypeOf((*MockService)(nil).RemoveEntity), ctx, input)
}
