// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/repositories/combatlog (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go -package=combatlogmock github.com/KirkDiggler/rpg-api/internal/repositories/combatlog Repository
//

// Package combatlogmock is a generated GoMock package.
package combatlogmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	combatlog "github.com/KirkDiggler/rpg-api/internal/repositories/combatlog"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(ctx context.Context, input *combatlog.AppendInput) (*combatlog.AppendOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, input)
	ret0, _ := ret[0].(*combatlog.AppendOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), ctx, input)
}

// GetByEncounter mocks base method.
func (m *MockRepository) GetByEncounter(ctx context.Context, input *combatlog.GetByEncounterInput) (*combatlog.GetByEncounterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEncounter", ctx, input)
	ret0, _ := ret[0].(*combatlog.GetByEncounterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEncounter indicates an expected call of GetByEncounter.
func (mr *MockRepositoryMockRecorder) GetByEncounter(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEncounter", reflect.TypeOf((*MockRepository)(nil).GetByEncounter), ctx, input)
}
