// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_service.go -package=encountermock github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter Service
//

// Package encountermock is a generated GoMock package.
package encountermock

import (
	context "context"
	reflect "reflect"

	encounter "github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ResolveAttack mocks base method.
func (m *MockService) ResolveAttack(ctx context.Context, input *encounter.ResolveAttackInput) (*encounter.ResolveAttackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAttack", ctx, input)
	ret0, _ := ret[0].(*encounter.ResolveAttackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAttack indicates an expected call of ResolveAttack.
func (mr *MockServiceMockRecorder) ResolveAttack(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAttack", reflect.TypeOf((*MockService)(nil).ResolveAttack), ctx, input)
}
