// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_service.go -package=encountermock github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter Service
//

// Package encountermock is a generated GoMock package.
package encountermock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	encounter "github.com/KirkDiggler/rpg-api/internal/orchestrators/encounter"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ActivateFeature mocks base method.
func (m *MockService) ActivateFeature(ctx context.Context, input *encounter.ActivateFeatureInput) (*encounter.ActivateFeatureOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateFeature", ctx, input)
	ret0, _ := ret[0].(*encounter.ActivateFeatureOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateFeature indicates an expected call of ActivateFeature.
func (mr *MockServiceMockRecorder) ActivateFeature(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateFeature", reflect.TypeOf((*MockService)(nil).ActivateFeature), ctx, input)
}

// CreateDungeon mocks base method.
func (m *MockService) CreateDungeon(ctx context.Context, input *encounter.CreateDungeonInput) (*encounter.CreateDungeonOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDungeon", ctx, input)
	ret0, _ := ret[0].(*encounter.CreateDungeonOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDungeon indicates an expected call of CreateDungeon.
func (mr *MockServiceMockRecorder) CreateDungeon(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDungeon", reflect.TypeOf((*MockService)(nil).CreateDungeon), ctx, input)
}

// EndTurn mocks base method.
func (m *MockService) EndTurn(ctx context.Context, input *encounter.EndTurnInput) (*encounter.EndTurnOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndTurn", ctx, input)
	ret0, _ := ret[0].(*encounter.EndTurnOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndTurn indicates an expected call of EndTurn.
func (mr *MockServiceMockRecorder) EndTurn(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndTurn", reflect.TypeOf((*MockService)(nil).EndTurn), ctx, input)
}

// MoveCharacter mocks base method.
func (m *MockService) MoveCharacter(ctx context.Context, input *encounter.MoveCharacterInput) (*encounter.MoveCharacterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCharacter", ctx, input)
	ret0, _ := ret[0].(*encounter.MoveCharacterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveCharacter indicates an expected call of MoveCharacter.
func (mr *MockServiceMockRecorder) MoveCharacter(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCharacter", reflect.TypeOf((*MockService)(nil).MoveCharacter), ctx, input)
}

// ResolveAttack mocks base method.
func (m *MockService) ResolveAttack(ctx context.Context, input *encounter.ResolveAttackInput) (*encounter.ResolveAttackOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAttack", ctx, input)
	ret0, _ := ret[0].(*encounter.ResolveAttackOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAttack indicates an expected call of ResolveAttack.
func (mr *MockServiceMockRecorder) ResolveAttack(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAttack", reflect.TypeOf((*MockService)(nil).ResolveAttack), ctx, input)
}
