// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/handlers/api/world/v1alpha1 (interfaces: Orchestrator)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_orchestrator.go -package=worldv1alpha1mock github.com/KirkDiggler/rpg-api/internal/handlers/api/world/v1alpha1 Orchestrator
//

// Package worldv1alpha1mock is a generated GoMock package.
package worldv1alpha1mock

import (
	context "context"
	reflect "reflect"

	world "github.com/KirkDiggler/rpg-api/internal/orchestrators/world"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestrator is a mock of Orchestrator interface.
type MockOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorMockRecorder
	isgomock struct{}
}

// MockOrchestratorMockRecorder is the mock recorder for MockOrchestrator.
type MockOrchestratorMockRecorder struct {
	mock *MockOrchestrator
}

// NewMockOrchestrator creates a new mock instance.
func NewMockOrchestrator(ctrl *gomock.Controller) *MockOrchestrator {
	mock := &MockOrchestrator{ctrl: ctrl}
	mock.recorder = &MockOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrator) EXPECT() *MockOrchestratorMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOrchestrator) Get(arg0 context.Context, arg1 *world.GetInput) (*world.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*world.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrchestratorMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrchestrator)(nil).Get), arg0, arg1)
}

// SetMemberRoles mocks base method.
func (m *MockOrchestrator) SetMemberRoles(arg0 context.Context, arg1 *world.SetMemberRolesInput) (*world.SetMemberRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemberRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetMemberRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMemberRoles indicates an expected call of SetMemberRoles.
func (mr *MockOrchestratorMockRecorder) SetMemberRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemberRoles", reflect.TypeOf((*MockOrchestrator)(nil).SetMemberRoles), arg0, arg1)
}

// SetRoles mocks base method.
func (m *MockOrchestrator) SetRoles(arg0 context.Context, arg1 *world.SetRolesInput) (*world.SetRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockOrchestratorMockRecorder) SetRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockOrchestrator)(nil).SetRoles), arg0, arg1)
}
