// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/services/world (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_service.go -package=worldmock github.com/KirkDiggler/rpg-api/internal/services/world Service
//

// Package worldmock is a generated GoMock package.
package worldmock

import (
	context "context"
	reflect "reflect"

	world "github.com/KirkDiggler/rpg-api/internal/services/world"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockService) Get(arg0 context.Context, arg1 *world.GetInput) (*world.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*world.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), arg0, arg1)
}

// SetMemberRoles mocks base method.
func (m *MockService) SetMemberRoles(arg0 context.Context, arg1 *world.SetMemberRolesInput) (*world.SetMemberRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemberRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetMemberRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMemberRoles indicates an expected call of SetMemberRoles.
func (mr *MockServiceMockRecorder) SetMemberRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemberRoles", reflect.TypeOf((*MockService)(nil).SetMemberRoles), arg0, arg1)
}

// SetRoles mocks base method.
func (m *MockService) SetRoles(arg0 context.Context, arg1 *world.SetRolesInput) (*world.SetRolesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoles", arg0, arg1)
	ret0, _ := ret[0].(*world.SetRolesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockServiceMockRecorder) SetRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockService)(nil).SetRoles), arg0, arg1)
}
