// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/repositories/character (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go -package=charactermock github.com/KirkDiggler/rpg-api/internal/repositories/character Repository
//

// Package charactermock is a generated GoMock package.
package charactermock

import (
	context "context"
	reflect "reflect"

	character "github.com/KirkDiggler/rpg-api/internal/repositories/character"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, input character.CreateInput) (*character.CreateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*character.CreateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, input character.DeleteInput) (*character.DeleteOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*character.DeleteOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, input character.GetInput) (*character.GetOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*character.GetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, input)
}

// ListByPlayerID mocks base method.
func (m *MockRepository) ListByPlayerID(ctx context.Context, input character.ListByPlayerIDInput) (*character.ListByPlayerIDOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPlayerID", ctx, input)
	ret0, _ := ret[0].(*character.ListByPlayerIDOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPlayerID indicates an expected call of ListByPlayerID.
func (mr *MockRepositoryMockRecorder) ListByPlayerID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPlayerID", reflect.TypeOf((*MockRepository)(nil).ListByPlayerID), ctx, input)
}

// ListBySessionID mocks base method.
func (m *MockRepository) ListBySessionID(ctx context.Context, input character.ListBySessionIDInput) (*character.ListBySessionIDOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySessionID", ctx, input)
	ret0, _ := ret[0].(*character.ListBySessionIDOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySessionID indicates an expected call of ListBySessionID.
func (mr *MockRepositoryMockRecorder) ListBySessionID(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySessionID", reflect.TypeOf((*MockRepository)(nil).ListBySessionID), ctx, input)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, input character.UpdateInput) (*character.UpdateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*character.UpdateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, input)
}
