// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KirkDiggler/rpg-api/internal/repositories/composition (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_repository.go -package=compositionmock github.com/KirkDiggler/rpg-api/internal/repositories/composition Repository
//

// Package compositionmock is a generated GoMock package.
package compositionmock

import (
	context "context"
	reflect "reflect"

	composition "github.com/KirkDiggler/rpg-api/internal/repositories/composition"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AppendRevision mocks base method.
func (m *MockRepository) AppendRevision(arg0 context.Context, arg1 composition.AppendRevisionInput) (*composition.AppendRevisionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRevision", arg0, arg1)
	ret0, _ := ret[0].(*composition.AppendRevisionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendRevision indicates an expected call of AppendRevision.
func (mr *MockRepositoryMockRecorder) AppendRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRevision", reflect.TypeOf((*MockRepository)(nil).AppendRevision), arg0, arg1)
}

// CreateDefinition mocks base method.
func (m *MockRepository) CreateDefinition(arg0 context.Context, arg1 composition.CreateDefinitionInput) (*composition.CreateDefinitionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefinition", arg0, arg1)
	ret0, _ := ret[0].(*composition.CreateDefinitionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDefinition indicates an expected call of CreateDefinition.
func (mr *MockRepositoryMockRecorder) CreateDefinition(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefinition", reflect.TypeOf((*MockRepository)(nil).CreateDefinition), arg0, arg1)
}

// GetRevision mocks base method.
func (m *MockRepository) GetRevision(arg0 context.Context, arg1 composition.GetRevisionInput) (*composition.GetRevisionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", arg0, arg1)
	ret0, _ := ret[0].(*composition.GetRevisionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockRepositoryMockRecorder) GetRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockRepository)(nil).GetRevision), arg0, arg1)
}

// ListDefinitions mocks base method.
func (m *MockRepository) ListDefinitions(arg0 context.Context, arg1 composition.ListDefinitionsInput) (*composition.ListDefinitionsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefinitions", arg0, arg1)
	ret0, _ := ret[0].(*composition.ListDefinitionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefinitions indicates an expected call of ListDefinitions.
func (mr *MockRepositoryMockRecorder) ListDefinitions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefinitions", reflect.TypeOf((*MockRepository)(nil).ListDefinitions), arg0, arg1)
}
