package encounterlog

import (
	"context"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/suite"

	"github.com/KirkDiggler/rpg-api/internal/entities"
	"github.com/KirkDiggler/rpg-api/internal/pkg/idgen"
)

type InMemoryRepositoryTestSuite struct {
	suite.Suite
	repo *InMemoryRepository
	ctx  context.Context
}

func (s *InMemoryRepositoryTestSuite) SetupTest() {
	// Use sequential generator for predictable IDs in tests
	s.repo = NewInMemory(&InMemoryConfig{
		IDGenerator: idgen.NewSequential("evt"),
	})
	s.ctx = context.Background()
}

func TestInMemoryRepositorySuite(t *testing.T) {
	suite.Run(t, new(InMemoryRepositoryTestSuite))
}

// Helper to create test events (ID will be generated by repo)
func (s *InMemoryRepositoryTestSuite) createEvent(encounterID string) *entities.EncounterEvent {
	return &entities.EncounterEvent{
		EncounterID: encounterID,
		Type:        entities.EventTypeAttackResolved,
		Timestamp:   time.Now(),
	}
}

// Append Tests

func (s *InMemoryRepositoryTestSuite) TestAppend_Success() {
	// Arrange
	event := s.createEvent("enc-1")
	input := &AppendInput{Event: event}

	// Act
	output, err := s.repo.Append(s.ctx, input)

	// Assert
	s.Require().NoError(err)
	s.Assert().Equal("evt_1", output.EventID)
	s.Assert().Equal("evt_1", event.ID, "Event should have ID populated by repo")
}

func (s *InMemoryRepositoryTestSuite) TestAppend_GeneratesUniqueIDs() {
	// Arrange & Act - Append multiple events
	var ids []string
	for i := 0; i < 5; i++ {
		output, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
		ids = append(ids, output.EventID)
	}

	// Assert - All IDs should be unique
	idSet := make(map[string]bool)
	for _, id := range ids {
		s.Assert().False(idSet[id], "Duplicate ID found: %s", id)
		idSet[id] = true
	}
}

func (s *InMemoryRepositoryTestSuite) TestAppend_NilInput() {
	// Act
	output, err := s.repo.Append(s.ctx, nil)

	// Assert
	s.Require().Error(err)
	s.Assert().Nil(output)
	s.Assert().Contains(err.Error(), "event is required")
}

func (s *InMemoryRepositoryTestSuite) TestAppend_NilEvent() {
	// Arrange
	input := &AppendInput{Event: nil}

	// Act
	output, err := s.repo.Append(s.ctx, input)

	// Assert
	s.Require().Error(err)
	s.Assert().Nil(output)
	s.Assert().Contains(err.Error(), "event is required")
}

func (s *InMemoryRepositoryTestSuite) TestAppend_EmptyEncounterID() {
	// Arrange
	event := &entities.EncounterEvent{
		EncounterID: "",
	}
	input := &AppendInput{Event: event}

	// Act
	output, err := s.repo.Append(s.ctx, input)

	// Assert
	s.Require().Error(err)
	s.Assert().Nil(output)
	s.Assert().Contains(err.Error(), "encounter ID is required")
}

func (s *InMemoryRepositoryTestSuite) TestAppend_MultipleEventsPreservesOrder() {
	// Arrange & Act - Append 3 events
	for i := 0; i < 3; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Get all events
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-1"})

	// Assert - Order should be preserved (sequential IDs: evt_1, evt_2, evt_3)
	s.Require().NoError(err)
	s.Require().Len(output.Events, 3)
	s.Assert().Equal("evt_1", output.Events[0].ID)
	s.Assert().Equal("evt_2", output.Events[1].ID)
	s.Assert().Equal("evt_3", output.Events[2].ID)
}

// GetByEncounter Tests

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_NilInput() {
	// Act
	output, err := s.repo.GetByEncounter(s.ctx, nil)

	// Assert
	s.Require().Error(err)
	s.Assert().Nil(output)
	s.Assert().Contains(err.Error(), "input is required")
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_EmptyEncounterID() {
	// Arrange
	input := &GetByEncounterInput{EncounterID: ""}

	// Act
	output, err := s.repo.GetByEncounter(s.ctx, input)

	// Assert
	s.Require().Error(err)
	s.Assert().Nil(output)
	s.Assert().Contains(err.Error(), "encounter ID is required")
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_NoEvents() {
	// Act
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-empty"})

	// Assert
	s.Require().NoError(err)
	s.Assert().NotNil(output.Events)
	s.Assert().Len(output.Events, 0)
	s.Assert().False(output.HasMore)
	s.Assert().Empty(output.LastEventID)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_ReturnsAllEvents() {
	// Arrange - Add 5 events
	for i := 0; i < 5; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-1"})

	// Assert
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 5)
	s.Assert().False(output.HasMore)
	s.Assert().Equal("evt_5", output.LastEventID)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_WithLimit() {
	// Arrange - Add 5 events
	for i := 0; i < 5; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act - Limit to 3
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-1",
		Limit:       3,
	})

	// Assert
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 3)
	s.Assert().True(output.HasMore)
	s.Assert().Equal("evt_3", output.LastEventID)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_LimitGreaterThanEvents() {
	// Arrange - Add 3 events
	for i := 0; i < 3; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act - Limit to 10 (more than available)
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-1",
		Limit:       10,
	})

	// Assert
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 3)
	s.Assert().False(output.HasMore)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_WithUpToEventID() {
	// Arrange - Add 5 events
	for i := 0; i < 5; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act - Get up to evt_3 (for late join scenario)
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-1",
		UpToEventID: "evt_3",
	})

	// Assert - Should return events 1, 2, 3 (inclusive)
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 3)
	s.Assert().Equal("evt_1", output.Events[0].ID)
	s.Assert().Equal("evt_2", output.Events[1].ID)
	s.Assert().Equal("evt_3", output.Events[2].ID)
	s.Assert().False(output.HasMore)
	s.Assert().Equal("evt_3", output.LastEventID)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_UpToEventIDNotFound() {
	// Arrange - Add 3 events
	for i := 0; i < 3; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act - Request up to a non-existent event
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-1",
		UpToEventID: "evt-nonexistent",
	})

	// Assert - Should return all events (target not found, so no cutoff)
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 3)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_UpToEventIDWithLimit() {
	// Arrange - Add 10 events
	for i := 0; i < 10; i++ {
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-1")})
		s.Require().NoError(err)
	}

	// Act - Get up to evt_8 with limit 3
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-1",
		UpToEventID: "evt_8",
		Limit:       3,
	})

	// Assert - Limit should take precedence
	s.Require().NoError(err)
	s.Assert().Len(output.Events, 3)
	s.Assert().True(output.HasMore)
	s.Assert().Equal("evt_3", output.LastEventID)
}

func (s *InMemoryRepositoryTestSuite) TestGetByEncounter_IsolatesEncounters() {
	// Arrange - Add events to different encounters
	_, err := s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-A")})
	s.Require().NoError(err)
	_, err = s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-B")})
	s.Require().NoError(err)
	_, err = s.repo.Append(s.ctx, &AppendInput{Event: s.createEvent("enc-A")})
	s.Require().NoError(err)

	// Act
	outputA, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-A"})
	s.Require().NoError(err)
	outputB, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-B"})
	s.Require().NoError(err)

	// Assert
	s.Assert().Len(outputA.Events, 2)
	s.Assert().Equal("evt_1", outputA.Events[0].ID)
	s.Assert().Equal("evt_3", outputA.Events[1].ID)

	s.Assert().Len(outputB.Events, 1)
	s.Assert().Equal("evt_2", outputB.Events[0].ID)
}

// Constructor Tests

func (s *InMemoryRepositoryTestSuite) TestNewInMemory_NilConfig_UsesULIDGenerator() {
	// Act
	repo := NewInMemory(nil)

	// Append an event
	output, err := repo.Append(s.ctx, &AppendInput{
		Event: &entities.EncounterEvent{
			EncounterID: "enc-1",
			Type:        entities.EventTypeAttackResolved,
			Timestamp:   time.Now(),
		},
	})

	// Assert - Should have generated a ULID (26 characters)
	s.Require().NoError(err)
	s.Assert().Len(output.EventID, 26, "ULID should be 26 characters")
}

func (s *InMemoryRepositoryTestSuite) TestNewInMemory_CustomGenerator() {
	// Arrange
	repo := NewInMemory(&InMemoryConfig{
		IDGenerator: idgen.NewSequential("custom"),
	})

	// Act
	output, err := repo.Append(s.ctx, &AppendInput{
		Event: &entities.EncounterEvent{
			EncounterID: "enc-1",
			Type:        entities.EventTypeAttackResolved,
			Timestamp:   time.Now(),
		},
	})

	// Assert
	s.Require().NoError(err)
	s.Assert().Equal("custom_1", output.EventID)
}

// Concurrency Tests

func (s *InMemoryRepositoryTestSuite) TestConcurrentAccess() {
	// Test concurrent appends and reads
	var wg sync.WaitGroup
	numGoroutines := 10
	eventsPerGoroutine := 10

	// Concurrent appends
	for g := 0; g < numGoroutines; g++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := 0; i < eventsPerGoroutine; i++ {
				event := &entities.EncounterEvent{
					EncounterID: "enc-concurrent",
					Type:        entities.EventTypeMovementCompleted,
					Timestamp:   time.Now(),
				}
				_, err := s.repo.Append(s.ctx, &AppendInput{Event: event})
				s.Assert().NoError(err)
			}
		}()
	}

	// Concurrent reads while appending
	for g := 0; g < 5; g++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := 0; i < 20; i++ {
				_, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-concurrent"})
				s.Assert().NoError(err)
			}
		}()
	}

	wg.Wait()

	// Verify all events were appended
	output, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{EncounterID: "enc-concurrent"})
	s.Require().NoError(err)
	s.Assert().Equal(numGoroutines*eventsPerGoroutine, len(output.Events))
}

// Integration Tests

func (s *InMemoryRepositoryTestSuite) TestWorkflow_LateJoinScenario() {
	// Simulate: Combat starts, events happen, player joins late

	// 1. Combat starts, several events happen
	eventTypes := []entities.EventType{
		entities.EventTypeCombatStarted,
		entities.EventTypeMovementCompleted,
		entities.EventTypeAttackResolved,
		entities.EventTypeTurnEnded,
		entities.EventTypeMovementCompleted,
		entities.EventTypeAttackResolved,
	}

	for _, evtType := range eventTypes {
		event := &entities.EncounterEvent{
			EncounterID: "enc-latejoin",
			Type:        evtType,
			Timestamp:   time.Now(),
		}
		_, err := s.repo.Append(s.ctx, &AppendInput{Event: event})
		s.Require().NoError(err)
	}

	// 2. Player joins late - GetEncounterState returns lastEventID = "evt_4"
	// They need history up to that point
	historyOutput, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-latejoin",
		UpToEventID: "evt_4",
	})

	// Assert - Should get events 1-4
	s.Require().NoError(err)
	s.Assert().Len(historyOutput.Events, 4)
	s.Assert().Equal("evt_1", historyOutput.Events[0].ID)
	s.Assert().Equal("evt_4", historyOutput.Events[3].ID)

	// 3. Player can also get all events (for full log)
	allOutput, err := s.repo.GetByEncounter(s.ctx, &GetByEncounterInput{
		EncounterID: "enc-latejoin",
	})
	s.Require().NoError(err)
	s.Assert().Len(allOutput.Events, 6)
}
